### ISSUE TITLE
US2: Medlemskontingent 

### ISSUE THREAD

**Issue by hajisan** [hajisan/Delfinen#16]
Som **kasserer** vil jeg gerne have et overblik over **medlemmers kontingent**, så jeg kan sende **påmindelse** på **overskredet** **betalinger** 

** TASKS
- [ ] 2.1 Opret en Kontigent-klasse med attributes, medlemsID, forfaldsdato, og status 
- [ ] 2.2 Tilføj metode der kan tildele et kontigent til et medlem (evt. Have flere kontigenter per person?) 
- [ ] 2.3 Opret en metode i FilStyrer, der læser alle medlemmer og deres kontigenter 
- [ ] 2.4 Implementer en metode findOverskredneBetalinger() i en KontigentStyrer-interface(Klasse?), som returnerer en liste over medlemmer med manglende betaling 
- [ ] 2.5 Opret en metode sendPåmindelse() i KontigentStyrer, som viser overskredne medlemmer med rødt
